/** Type de restaurant : valeur API (fr) → libellés par langue */
export const RESTAURANT_TYPE_LABELS = {
  'Restaurant à la carte': {
    fr: 'Restaurant à la carte',
    en: 'À la carte restaurant',
    es: 'Restaurante a la carta',
    it: 'Ristorante à la carte',
    de: 'À-la-carte-Restaurant',
    ar: 'مطعم حسب الطلب',
  },
  'Restaurant Self-Service': {
    fr: 'Restaurant Self-Service',
    en: 'Self-service restaurant',
    es: 'Restaurante autoservicio',
    it: 'Ristorante self-service',
    de: 'Selbstbedienungsrestaurant',
    ar: 'مطعم self-service',
  },
  'Café & Snacks': {
    fr: 'Café & Snacks',
    en: 'Café & Snacks',
    es: 'Café y snacks',
    it: 'Caffè e snack',
    de: 'Café & Snacks',
    ar: 'مقهى ووجبات خفيفة',
  },
  'Pizzeria saisonnière': {
    fr: 'Pizzeria saisonnière',
    en: 'Seasonal pizzeria',
    es: 'Pizzería de temporada',
    it: 'Pizzeria stagionale',
    de: 'Saisonale Pizzeria',
    ar: 'بيتزا موسمية',
  },
  Steakhouse: {
    fr: 'Steakhouse',
    en: 'Steakhouse',
    es: 'Steakhouse',
    it: 'Steakhouse',
    de: 'Steakhouse',
    ar: 'ستيك هاوس',
  },
  'Room Service': {
    fr: 'Room Service',
    en: 'Room service',
    es: 'Servicio de habitaciones',
    it: 'Servizio in camera',
    de: 'Zimmerservice',
    ar: 'خدمة الغرف',
  },
};

/** Catégorie de plat (menu) : clé → libellés par langue */
export const MENU_CATEGORY_LABELS = {
  appetizer: { fr: 'Entrée', en: 'Starter', es: 'Entrante', it: 'Antipasto', de: 'Vorspeise', ar: 'مقبلات' },
  main: {
    fr: 'Plat principal',
    en: 'Main course',
    es: 'Plato principal',
    it: 'Piatto principale',
    de: 'Hauptgericht',
    ar: 'الطبق الرئيسي',
  },
  dessert: { fr: 'Dessert', en: 'Dessert', es: 'Postre', it: 'Dolce', de: 'Nachtisch', ar: 'حلوى' },
  beverage: { fr: 'Boisson', en: 'Beverage', es: 'Bebida', it: 'Bevanda', de: 'Getränk', ar: 'مشروب' },
  wine: { fr: 'Vin', en: 'Wine', es: 'Vino', it: 'Vino', de: 'Wein', ar: 'نبيذ' },
  cocktail: { fr: 'Cocktail', en: 'Cocktail', es: 'Cóctel', it: 'Cocktail', de: 'Cocktail', ar: 'كوكتيل' },
  other: { fr: 'Autre', en: 'Other', es: 'Otro', it: 'Altro', de: 'Sonstige', ar: 'آخر' },
};

/** Catégorie restaurant (french, fastfood, etc.) */
export const RESTAURANT_CATEGORY_LABELS = {
  french: { fr: 'Français', en: 'French', es: 'Francés', it: 'Francese', de: 'Französisch', ar: 'فرنسي' },
  fastfood: {
    fr: 'Fast-food',
    en: 'Fast food',
    es: 'Comida rápida',
    it: 'Fast food',
    de: 'Fastfood',
    ar: 'وجبات سريعة',
  },
  dessert: { fr: 'Dessert', en: 'Dessert', es: 'Postres', it: 'Dolce', de: 'Dessert', ar: 'حلويات' },
  seafood: {
    fr: 'Fruits de mer',
    en: 'Seafood',
    es: 'Mariscos',
    it: 'Frutti di mare',
    de: 'Meeresfrüchte',
    ar: 'مأكولات بحرية',
  },
};

const RESTAURANT_FORM_LABELS = {
  fr: {
    restaurantTypeLabel: 'Type de restaurant',
    type: 'Type',
    shipLabel: 'Bateau',
    selectPlaceholder: 'Sélectionner...',
    selectShipPlaceholder: 'Sélectionner un bateau...',
    locationLabel: 'Localisation',
    locationPlaceholder: 'Ex : Pont 7, Niveau 2',
    priceRangeLabel: 'Fourchette de prix',
    priceRangeBudget: '€ Économique',
    priceRangeModerate: '€€ Modéré',
    priceRangeHigh: '€€€ Élevé',
    priceRangeVeryHigh: '€€€€ Très élevé',
    openingHoursLabel: "Heures d'ouverture",
    openingHoursPlaceholder: 'Ex : 08:00 - 22:00',
  },
  en: {
    restaurantTypeLabel: 'Restaurant type',
    type: 'Type',
    shipLabel: 'Ship',
    selectPlaceholder: 'Select...',
    selectShipPlaceholder: 'Select a ship...',
    locationLabel: 'Location',
    locationPlaceholder: 'E.g. Deck 7, Level 2',
    priceRangeLabel: 'Price range',
    priceRangeBudget: '€ Budget',
    priceRangeModerate: '€€ Moderate',
    priceRangeHigh: '€€€ High',
    priceRangeVeryHigh: '€€€€ Very high',
    openingHoursLabel: 'Opening hours',
    openingHoursPlaceholder: 'E.g. 08:00 - 22:00',
  },
  es: {
    restaurantTypeLabel: 'Tipo de restaurante',
    type: 'Tipo',
    shipLabel: 'Barco',
    selectPlaceholder: 'Seleccionar...',
    selectShipPlaceholder: 'Seleccione un barco...',
    locationLabel: 'Ubicación',
    locationPlaceholder: 'Ej: Cubierta 7, Nivel 2',
    priceRangeLabel: 'Rango de precios',
    priceRangeBudget: '€ Económico',
    priceRangeModerate: '€€ Moderado',
    priceRangeHigh: '€€€ Alto',
    priceRangeVeryHigh: '€€€€ Muy alto',
    openingHoursLabel: 'Horario de apertura',
    openingHoursPlaceholder: 'Ej: 08:00 - 22:00',
  },
  it: {
    restaurantTypeLabel: 'Tipo di ristorante',
    type: 'Tipo',
    shipLabel: 'Nave',
    selectPlaceholder: 'Seleziona...',
    selectShipPlaceholder: 'Seleziona una nave...',
    locationLabel: 'Posizione',
    locationPlaceholder: 'Es: Ponte 7, Livello 2',
    priceRangeLabel: 'Fascia di prezzo',
    priceRangeBudget: '€ Economico',
    priceRangeModerate: '€€ Moderato',
    priceRangeHigh: '€€€ Alto',
    priceRangeVeryHigh: '€€€€ Molto alto',
    openingHoursLabel: 'Orari di apertura',
    openingHoursPlaceholder: 'Es: 08:00 - 22:00',
  },
  de: {
    restaurantTypeLabel: 'Restauranttyp',
    type: 'Typ',
    shipLabel: 'Schiff',
    selectPlaceholder: 'Auswählen...',
    selectShipPlaceholder: 'Schiff auswählen...',
    locationLabel: 'Standort',
    locationPlaceholder: 'z. B. Deck 7, Ebene 2',
    priceRangeLabel: 'Preisklasse',
    priceRangeBudget: '€ Günstig',
    priceRangeModerate: '€€ Mittel',
    priceRangeHigh: '€€€ Gehoben',
    priceRangeVeryHigh: '€€€€ Sehr gehoben',
    openingHoursLabel: 'Öffnungszeiten',
    openingHoursPlaceholder: 'z. B. 08:00 - 22:00',
  },
  ar: {
    restaurantTypeLabel: 'نوع المطعم',
    type: 'النوع',
    shipLabel: 'السفينة',
    selectPlaceholder: 'اختر...',
    selectShipPlaceholder: 'اختر سفينة...',
    locationLabel: 'الموقع',
    locationPlaceholder: 'مثال: السطح 7، المستوى 2',
    priceRangeLabel: 'نطاق السعر',
    priceRangeBudget: '€ اقتصادي',
    priceRangeModerate: '€€ متوسط',
    priceRangeHigh: '€€€ مرتفع',
    priceRangeVeryHigh: '€€€€ مرتفع جداً',
    openingHoursLabel: 'ساعات العمل',
    openingHoursPlaceholder: 'مثال: 08:00 - 22:00',
  },
};

export function getFormLabel(lang, key) {
  return RESTAURANT_FORM_LABELS[lang]?.[key] ?? RESTAURANT_FORM_LABELS.fr[key] ?? key;
}
